//////////////////////////////////////////////////////////////
//                                                          //
// This testbench has been generated by the Verilog         //
// testbench generator                .                     //
// Copyright (c) 2012-2022 EDAUtils LLP                 //
// Contact help@edautils.com  for support/info.//
//                                                          //
//                                                          //
//////////////////////////////////////////////////////////////
//
//
// Generated by : Vincent on 18/01/24 13:54
//
//
module testbench;
	reg [0:1] indata_array;
	reg bench_clk1;
	reg bench_clk2;
	reg bench_rst1;
	reg bench_rst2;
	wire bench_in1;
	wire bench_in2;
	wire bench_out1;
	wire bench_out2;


	event e_clk1;
	event e_clk2;

	assign bench_in1 = indata_array[0:0];
	assign bench_in2 = indata_array[1:1];

	initial
	begin
		#0  bench_clk1 = 1'b0;
	end

	always
	begin
		#8 bench_clk1 = !bench_clk1;
		->e_clk1;
	end

	initial
	begin
		#0  bench_clk2 = 1'b0;
	end

	always
	begin
		#5 bench_clk2 = !bench_clk2;
		->e_clk2;
	end

	initial
	begin
		#10 bench_rst1 = 1'b0;
	end

	initial
	begin
		#5 bench_rst2 = 1'b1;
		#50 bench_rst2 = 1'b0;
		#150 bench_rst2 = 1'b1;
	end

	always@( e_clk1 or e_clk2 )
	begin
		#5  indata_array = $random;
	end

	reset_waveforms inst(
        .clk1(bench_clk1), 
        .rst1(bench_rst1), 
        .clk2(bench_clk2), 
        .rst2(bench_rst2), 
        .in1(bench_in1), 
        .in2(bench_in2), 
        .out1(bench_out1), 
        .out2(bench_out2)
    );

	initial
	begin
		$monitor($time, " bench_rst1 = %b, bench_rst2 = %b, in1 = %b , in2 = %b , out1 = %b , out2 = %b  ",
			bench_rst1, bench_rst2, bench_in1, bench_in2, bench_out1, bench_out2);
	end

	initial
	begin
		#500 $finish;
	end

endmodule
